name = "SecureVault"
uuid = "a1b2c3d4-5678-90ab-cdef-111111111111"
authors = ["bad-antics <bad-antics@users.noreply.github.com>"]
version = "1.0.0"

[deps]
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[compat]
julia = "1.6"
